<?php

namespace AppBundle\Repository;

/**
 * EvaluacionProfesorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluacionProfesorRepository extends \Doctrine\ORM\EntityRepository
{
}
