<?php

namespace AppBundle\Repository;

/**
 * EvaluacionCuadroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluacionCuadroRepository extends \Doctrine\ORM\EntityRepository
{
}
