<?php

namespace AppBundle\Repository;

/**
 * ExpedienteCuadroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpedienteCuadroRepository extends \Doctrine\ORM\EntityRepository
{
}
