<?php

namespace AppBundle\Repository;

/**
 * ExpedienteProfesorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpedienteProfesorRepository extends \Doctrine\ORM\EntityRepository
{
}
