<?php

namespace AppBundle\Repository;

/**
 * MedidaDisciplinariaCuadroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedidaDisciplinariaCuadroRepository extends \Doctrine\ORM\EntityRepository
{
}
