<?php

namespace AppBundle\Repository;

/**
 * MovimientoCuadroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovimientoCuadroRepository extends \Doctrine\ORM\EntityRepository
{
}
