<?php

namespace AppBundle\Repository;

/**
 * NomencladorInfraccionDisciplinariaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomencladorInfraccionDisciplinariaRepository extends \Doctrine\ORM\EntityRepository
{
}
