<?php

namespace AppBundle\Repository;

/**
 * NomencladorCargoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomencladorCargoRepository extends \Doctrine\ORM\EntityRepository
{
}
