<?php

namespace AppBundle\Repository;

/**
 * NomencladorMaestriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomencladorMaestriaRepository extends \Doctrine\ORM\EntityRepository
{
}
