<?php

namespace AppBundle\Repository;

/**
 * NomencladorTipoMedidaDisciplinariaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomencladorTipoMedidaDisciplinariaRepository extends \Doctrine\ORM\EntityRepository
{
}
