<?php

namespace AppBundle\Repository;

/**
 * NomencladorResultadoEvaluacionProfesoralRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomencladorResultadoEvaluacionProfesoralRepository extends \Doctrine\ORM\EntityRepository
{
}
