<?php

namespace AppBundle\Repository;

/**
 * NomencladorMovimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomencladorMovimientoRepository extends \Doctrine\ORM\EntityRepository
{
}
