<?php

namespace AppBundle\Repository;

/**
 * NomencladorEstadoCivilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomencladorEstadoCivilRepository extends \Doctrine\ORM\EntityRepository
{
}
