<?php

namespace AppBundle\Repository;

/**
 * NomencladorResultadoReclamacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomencladorResultadoReclamacionRepository extends \Doctrine\ORM\EntityRepository
{
}
