<?php

namespace AppBundle\Repository;

/**
 * NomencladorProcedenciaSocialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomencladorProcedenciaSocialRepository extends \Doctrine\ORM\EntityRepository
{
}
