<?php

namespace AppBundle\Repository;

/**
 * NomencladorFacultadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomencladorFacultadRepository extends \Doctrine\ORM\EntityRepository
{
}
