<?php

namespace AppBundle\Repository;

/**
 * NomencladorLimitacionFisicaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomencladorLimitacionFisicaRepository extends \Doctrine\ORM\EntityRepository
{
}
