<?php

namespace AppBundle\Repository;

use AppBundle\Entity\NomencladorConsejoPopular;
use Doctrine\ORM\EntityRepository;
use Exception;

/**
 * NomencladorConsejoPopularRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomencladorConsejoPopularRepository extends EntityRepository
{
    public function agregarNomencladorConsejoPopular($data)
    {
        try {
            $em = $this->getEntityManager();
            $nomencladorConsejoPopular = new NomencladorConsejoPopular();
            $this->saveNomencladorConsejoPopular($nomencladorConsejoPopular,$data);
            $em->persist($nomencladorConsejoPopular);
            $em->flush();
            $msg = $nomencladorConsejoPopular;

        } catch (Exception $e) {
            if (strpos($e->getMessage(), 'Duplicate entry') > 0) {
                $msg = 'El consejo popular ya existe, no se puede agregar';
            } else {
                $msg = 'Se produjo un error al insertar el consejo popular';
            }
        }
        return $msg;
    }

    public function modificarNomencladorConsejoPopular($data)
    {
        try {
            $em = $this->getEntityManager();
            $nomencladorConsejoPopular = $em->getRepository('AppBundle:NomencladorConsejoPopular')->find($data['id']);

            if (!empty($nomencladorConsejoPopular)) {
                $this->saveNomencladorConsejoPopular($nomencladorConsejoPopular,$data);

                $em->flush();
                $msg = $nomencladorConsejoPopular;
            } else {
                $msg = $nomencladorConsejoPopular;
            }

        } catch (Exception $e) {
            $msg = 'Se produjo un error al modificar el consejo popular';
        }

        return $msg;
    }

    public function eliminarNomencladorConsejoPopular($id)
    {
        try {
            $em = $this->getEntityManager();
            $nomencladorEspecialidad = $em->getRepository('AppBundle:NomencladorEspecialidad')->find($id);

            if (!empty($nomencladorEspecialidad)) {
                $em->remove($nomencladorEspecialidad);
                $em->flush();
                $msg = $nomencladorEspecialidad;
            } else {
                $msg = $nomencladorEspecialidad;
            }

        } catch (Exception $e) {

            $msg = 'Se produjo un error al eliminar la especialidad';

        }
        return $msg;
    }

    private function saveNomencladorConsejoPopular($nomencladorConsejoPopular,$data){
        $nomencladorConsejoPopular->setNombre($data['nombre']);
    }
}
