<?php

namespace AppBundle\Repository;

/**
 * NomencladorMedidaDisciplinariaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomencladorMedidaDisciplinariaRepository extends \Doctrine\ORM\EntityRepository
{
}
