<?php

namespace AppBundle\Repository;

/**
 * NomencladorPreparacionMilitarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomencladorPreparacionMilitarRepository extends \Doctrine\ORM\EntityRepository
{
}
