<?php

namespace AppBundle\Repository;

/**
 * NomencladorAdministracionPublicaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomencladorAdministracionPublicaRepository extends \Doctrine\ORM\EntityRepository
{
}
