<?php

namespace AppBundle\Repository;

/**
 * NomencladorGrupoBasicoTrabajoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomencladorGrupoBasicoTrabajoRepository extends \Doctrine\ORM\EntityRepository
{
}
