<?php

namespace AppBundle\Repository;

/**
 * NomencladorEstadoSaludRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomencladorEstadoSaludRepository extends \Doctrine\ORM\EntityRepository
{
}
