<?php

namespace AppBundle\Repository;

/**
 * NomencladorTipoPreparacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomencladorTipoPreparacionRepository extends \Doctrine\ORM\EntityRepository
{
}
