<?php

namespace AppBundle\Repository;

/**
 * NomencladorProfesionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomencladorProfesionRepository extends \Doctrine\ORM\EntityRepository
{
}
