<?php

namespace AppBundle\Repository;

/**
 * NomencladorColorPeloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomencladorColorPeloRepository extends \Doctrine\ORM\EntityRepository
{
}
