<?php

namespace AppBundle\Repository;

/**
 * NomencladorCarreraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomencladorCarreraRepository extends \Doctrine\ORM\EntityRepository
{
}
