<?php

namespace AppBundle\Repository;

/**
 * NomencladorAsignaturaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomencladorAsignaturaRepository extends \Doctrine\ORM\EntityRepository
{
}
