<?php

namespace AppBundle\Repository;

/**
 * NomencladorGrupoSanguineoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomencladorGrupoSanguineoRepository extends \Doctrine\ORM\EntityRepository
{
}
