<?php

namespace AppBundle\Repository;

/**
 * NomencladorNivelEscolarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomencladorNivelEscolarRepository extends \Doctrine\ORM\EntityRepository
{
}
