<?php

namespace AppBundle\Repository;

/**
 * NomencladorCiudadaniaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomencladorCiudadaniaRepository extends \Doctrine\ORM\EntityRepository
{
}
