<?php

namespace AppBundle\Repository;

/**
 * NomencladorCentroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomencladorCentroRepository extends \Doctrine\ORM\EntityRepository
{
}
