<?php

namespace AppBundle\Repository;

/**
 * NomencladorCategoriaCientificaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomencladorCategoriaCientificaRepository extends \Doctrine\ORM\EntityRepository
{
}
