<?php

namespace AppBundle\Repository;

/**
 * NomencladorTipoMovimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomencladorTipoMovimientoRepository extends \Doctrine\ORM\EntityRepository
{
}
