<?php

namespace AppBundle\Repository;

/**
 * NomencladorColorPielRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomencladorColorPielRepository extends \Doctrine\ORM\EntityRepository
{
}
