<?php

namespace AppBundle\Repository;

/**
 * NomencladorMilitanciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomencladorMilitanciaRepository extends \Doctrine\ORM\EntityRepository
{
}
