<?php

namespace AppBundle\Repository;

/**
 * NomencladorCursoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomencladorCursoRepository extends \Doctrine\ORM\EntityRepository
{
}
