<?php

namespace AppBundle\Repository;

/**
 * NomencladorMunicipioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomencladorMunicipioRepository extends \Doctrine\ORM\EntityRepository
{
}
