<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Exception;

/**
 * NomencladorEspecialidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomencladorEspecialidadRepository extends EntityRepository
{
    public function agregarNomenclador($nombre,$nomenclador)
    {
        try {
            $em = $this->getEntityManager();
            $this->saveNomenclador($nomenclador,$nombre);
            $em->persist($nomenclador);
            $em->flush();
            $msg = $nomenclador;

        } catch (Exception $e) {
            if (strpos($e->getMessage(), 'Duplicate entry') > 0) {
                $msg = 'El nomenclador ya existe, no se puede agregar';
            } else {
                $msg = 'Se produjo un error al insertar el nomenclador';
            }
        }
        return $msg;
    }

    public function modificarNomenclador($data)
    {
        try {
            $em = $this->getEntityManager();
            $nomenclador = $em->getRepository('AppBundle:' . $data['entidad'])->find($data['id']);

            if (!empty($nomenclador)) {
                $this->saveNomenclador($nomenclador,$data['nombre']);

                $em->flush();
                $msg = $nomenclador;
            } else {
                $msg = $nomenclador;
            }

        } catch (Exception $e) {
            $msg = 'Se produjo un error al modificar el nomenclador';
        }

        return $msg;
    }

    public function eliminarNomenclador($data)
    {
        try {
            $em = $this->getEntityManager();
            $nomenclador = $em->getRepository('AppBundle:'. $data['entidad'])->find($data['id']);

            if (!empty($nomenclador)) {
                $em->remove($nomenclador);
                $em->flush();
                $msg = $nomenclador;
            } else {
                $msg = $nomenclador;
            }

        } catch (Exception $e) {
            if (strpos($e->getMessage(), 'foreign key') > 0) {
                $msg = 'Existen datos asociados a este nomenclador, no se puede eliminar';
            } else {
                $msg = $msg = 'Se produjo un error al eliminar el nomenclador';
            }
        }
        return $msg;
    }

    private function saveNomenclador($nomencladorEspecialidad,$nombre){
        $nomencladorEspecialidad->setNombre(strtoupper($nombre));
    }

}
