<?php

namespace AppBundle\Repository;

/**
 * NomencladorProvinciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomencladorProvinciaRepository extends \Doctrine\ORM\EntityRepository
{
}
