<?php

namespace AppBundle\Repository;

/**
 * NomencladorGradoCientificoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomencladorGradoCientificoRepository extends \Doctrine\ORM\EntityRepository
{
}
