<?php

namespace AppBundle\Repository;

/**
 * NomencladorColorOjoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomencladorColorOjoRepository extends \Doctrine\ORM\EntityRepository
{
}
