<?php

namespace AppBundle\Repository;

/**
 * NomencladorDepartamentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomencladorDepartamentoRepository extends \Doctrine\ORM\EntityRepository
{
}
