<?php

namespace AppBundle\Repository;

/**
 * PlantillaCargoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlantillaCargoRepository extends \Doctrine\ORM\EntityRepository
{
}
