<?php

namespace AppBundle\Repository;

/**
 * ReservaCuadroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservaCuadroRepository extends \Doctrine\ORM\EntityRepository
{
}
