<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Traza;
use DateTime;
use Exception;

/**
 * TrazaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrazaRepository extends \Doctrine\ORM\EntityRepository
{
    public function guardarTraza($dataTraza)
    {
        try{
            $fecha = new DateTime('now');

            $em = $this->getEntityManager();
            $traza = new Traza();
            $traza->setFecha($fecha);
            $traza->setModulo($dataTraza['modulo']);
            $traza->setAccion($dataTraza['accion']);
            $traza->setDescripcion($dataTraza['descripcion']);

//            $usuario = $em->getRepository('AppBundle:Usuario')->find($user->getId());
//            $traza->setUsuario($usuario);

            $em->persist($traza);
            $em->flush();
            $msg = $traza;

        }catch (Exception $e)
        {
            $msg = 'Se produjo un error al insertar la traza';
        }
        return $msg;
    }
}
